/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as ChainRouteImport } from './routes/chain'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MemesRouteImport } from './routes/memes'
import { Route as MoonzoRouteImport } from './routes/moonzo'
import { Route as PheraRouteImport } from './routes/phera'
import { Route as RoadmapRouteImport } from './routes/roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainRoute = ChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MemesRoute = MemesRouteImport.update({
  id: '/memes',
  path: '/memes',
  getParentRoute: () => rootRouteImport,
} as any)
const MoonzoRoute = MoonzoRouteImport.update({
  id: '/moonzo',
  path: '/moonzo',
  getParentRoute: () => rootRouteImport,
} as any)
const PheraRoute = PheraRouteImport.update({
  id: '/phera',
  path: '/phera',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/chain': typeof ChainRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/memes': typeof MemesRoute
  '/moonzo': typeof MoonzoRoute
  '/phera': typeof PheraRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/chain': typeof ChainRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/memes': typeof MemesRoute
  '/moonzo': typeof MoonzoRoute
  '/phera': typeof PheraRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/chain': typeof ChainRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/memes': typeof MemesRoute
  '/moonzo': typeof MoonzoRoute
  '/phera': typeof PheraRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcade'
    | '/chain'
    | '/community'
    | '/faq'
    | '/legal'
    | '/memes'
    | '/moonzo'
    | '/phera'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcade'
    | '/chain'
    | '/community'
    | '/faq'
    | '/legal'
    | '/memes'
    | '/moonzo'
    | '/phera'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/arcade'
    | '/chain'
    | '/community'
    | '/faq'
    | '/legal'
    | '/memes'
    | '/moonzo'
    | '/phera'
    | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRoute
  ChainRoute: typeof ChainRoute
  CommunityRoute: typeof CommunityRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  MemesRoute: typeof MemesRoute
  MoonzoRoute: typeof MoonzoRoute
  PheraRoute: typeof PheraRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain': {
      id: '/chain'
      path: '/chain'
      fullPath: '/chain'
      preLoaderRoute: typeof ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memes': {
      id: '/memes'
      path: '/memes'
      fullPath: '/memes'
      preLoaderRoute: typeof MemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moonzo': {
      id: '/moonzo'
      path: '/moonzo'
      fullPath: '/moonzo'
      preLoaderRoute: typeof MoonzoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phera': {
      id: '/phera'
      path: '/phera'
      fullPath: '/phera'
      preLoaderRoute: typeof PheraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRoute,
  ChainRoute: ChainRoute,
  CommunityRoute: CommunityRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  MemesRoute: MemesRoute,
  MoonzoRoute: MoonzoRoute,
  PheraRoute: PheraRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
